version: "3.9"
services:
 
  frontend:
    image: nginx
    volumes:
     # - D:/VJ_Projects/SalesNet-DBO/ngnx.conf:/opt/h2-data
      - ./nginx.conf:/etc/nginx/nginx.conf
      #- ./reverse_proxy/nginx.conf:/opt/h2-data
    depends_on:
      - backend
    ports:
      - 4001:4001
    restart: unless-stopped
    networks:
      - nginx-network
  backend:
    build:
     context: ./
    expose: 
      - "5000"
      
    restart: unless-stopped
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
